nikoo/apps/deal/urls.py
from django.conf.urls import url, include

from nikoo.apps.deal.common_views import add_document, ajax_add_document, add_contract, ajax_add_contract, add_sgs, \
    ajax_add_sgs
from nikoo.apps.deal.purchase_views import *
from nikoo.apps.deal.views import *

urlpatterns = [
    url(r'^invoice/', include('nikoo.apps.invoice.urls')),

    url(r'^add_bill_slip/(?P<deal_id>\w+)/$', add_bill_slip, name='add_bill_slip'),

    url(r'^add_product_sell/(?P<deal_id>\d+)/$', add_product_sell, name='add_product_sell'),

    # url(r'^add_contract/(?P<deal_id>\d+)/$', add_contract, name='add_contract_product_deal'),
    # url(r'^ajax_add_contract/(?P<deal_id>\d+)/(?P<product_id>\d+)/$', ajax_add_contract, name='add_contract_deal_ajax'),



    url(r'^add_ciq/(?P<deal_id>\d+)/$', add_ciq, name='add_ciq_product_deal'),
    url(r'^ajax_add_ciq/(?P<deal_id>\d+)/(?P<product_id>\d+)/$', ajax_add_ciq, name='ajax_add_ciq'),

    # sell
    url(r'^add_sell/$', add_sell, name='add_sell'),
    url(r'^sell_edit/(?P<deal_id>\w+)/$', edit_sell, name='sell_edit'),
    url(r'^sell_view/(?P<deal_id>\w+)/$', sell_view, name='sell_view'),
    url(r'^sell_cancel/(?P<deal_id>\w+)/$', sell_cancel, name='sell_cancel'),

    url(r'^ship/(?P<deal_id>\w+)/$', ship_info, name='sell_ship'),

    # purchase
    url(r'^add_purchase/$', add_purchase, name='add_purchase'),
    url(r'^purchase_view/(?P<deal_id>\w+)/$', purchase_view, name='purchase_view'),
    url(r'^purchase_cancel/(?P<deal_id>\w+)/$', purchase_cancel, name='purchase_cancel'),
    url(r'^purchase_edit/(?P<deal_id>\w+)/$', edit_purchase, name='purchase_edit'),
    url(r'^add_product_purchase/(?P<deal_id>\d+)/$', add_product_purchase, name='add_product_purchase'),
    url(r'^add_cost_purchase/(?P<deal_id>\d+)/$', add_cost_purchase, name='add_cost_purchase'),

    # common
    url(r'^add_document/(?P<deal_id>\d+)/$', add_document, name='add_document_deal'),
    url(r'^ajax_add_document/(?P<deal_id>\d+)/(?P<document_id>\d+)/$', ajax_add_document,
        name='add_document_deal_ajax'),
    url(r'^add_contract/(?P<deal_id>\d+)/$', add_contract, name='add_contract_product_deal'),
    url(r'^ajax_add_contract/(?P<deal_id>\d+)/(?P<product_id>\d+)/$', ajax_add_contract, name='ajax_add_contract'),
    url(r'^add_sgs/(?P<deal_id>\d+)/$', add_sgs, name='add_sgs_product_deal'),
    url(r'^ajax_add_sgs/(?P<deal_id>\d+)/(?P<product_id>\d+)/$', ajax_add_sgs, name='ajax_add_sgs'),
]

nikoo/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.views.static import serve

from nikoo.apps.accounts.views import dashboard, permission_401
from nikoo.apps.utils import manager

urlpatterns = [
                  url('^i18n/', include('django.conf.urls.i18n')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^$', dashboard, name='dashboard'),
    url(r'^permission401', permission_401, name='permission_401'),

    url(r'^accounts/', include('nikoo.apps.accounts.urls')),
    url(r'^deal/', include('nikoo.apps.deal.urls')),
    url(r'^base/', include('nikoo.apps.base_information.urls')),
)

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        }),
    ]

manager.install_manager()

nikoo/apps/deal/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from nikoo.apps.base_information.models import DocumentSpec
from nikoo.apps.utils.file import bill_slip_upload_to, deal_file_upload_to
from nikoo.apps.utils.models import LogicalDeletedManager


class Deal(models.Model):
    PURCHASE = 1
    SELL = 2
    DEAL_TYPE = (
        (PURCHASE, _("deal")),
        (SELL, _("Sell")),
    )

    WORK = 1
    FOT = 2
    FOB = 3
    CFR = 4
    AGREEMENT_TYPE_CHOICE = (
        (WORK, _("ExWORK")),
        (FOT, _("FOT")),
        (FOB, _("FOB")),
        (CFR, _("CFR")),
    )

    PLATTS = 1
    UMETAL = 2
    FIXED = 3
    INDEX_TYPES_CHOICE = (
        (PLATTS, _("PLATTS")),
        (UMETAL, _("UMETAL")),
        (FIXED, _("FIXED")),
    )

    IN_PROGRESS = 1
    FINISHED = 2
    DRAFT = 3
    CANCELED = 4
    ARCHIVE = 5
    STATE_CHOICES = (
        (IN_PROGRESS, _("In progress")),
        (FINISHED, _("Completed")),
        (DRAFT, _("Draft")),
        (CANCELED, _("Canceled")),
        (ARCHIVE, _("Archive")),
    )

    PERIOD_CHOICES = ((0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10),)

    deal_type = models.IntegerField(_("Deal type"), choices=DEAL_TYPE, default=PURCHASE)
    agreement_no = models.CharField(_("Agreement number"), max_length=50)
    vessel_name = models.CharField(_("Vessel name"), max_length=100)
    agreement_types = models.IntegerField(_("Agreement types"), choices=AGREEMENT_TYPE_CHOICE, default=WORK)
    project_date = models.DateField(_("Project date"))
    index_types = models.ForeignKey('base_information.Reference', verbose_name=_("Index types"),
                                    related_name='deal_reference')
    period = models.IntegerField(_("Period"), choices=PERIOD_CHOICES, default=2)
    index_date = models.DateField(_("Index Date"))
    index_price = models.DecimalField(_("Index price"), max_digits=9, decimal_places=4, default=0)
    down_payment = models.DecimalField(_("Down Payment"), max_digits=15, decimal_places=4, default=0)
    description = models.TextField(_("Description"), null=True, blank=True)
    ship = models.ForeignKey('base_information.Ship', verbose_name=_("Ship name"), null=True, blank=True)
    my_company = models.ForeignKey('MyCompany', verbose_name=_("My Company"))
    mine = models.ForeignKey('Mine', verbose_name=_("Mine"), null=True, blank=True)
    state = models.IntegerField(_("Status"), choices=STATE_CHOICES, default=IN_PROGRESS)
    documents = models.ManyToManyField('base_information.Document', blank=True)
    from_step1 = models.DecimalField(_("Greater than"), max_digits=9, decimal_places=4, default=0)
    viu_step1 = models.DecimalField(_("Viu"), max_digits=9, decimal_places=4, default=0)
    from_step2 = models.DecimalField(_("From"), max_digits=9, decimal_places=4, default=0)
    to_step2 = models.DecimalField(_("To"), max_digits=9, decimal_places=4, default=0)
    viu_step2 = models.DecimalField(_("Viu"), max_digits=9, decimal_places=4, default=0)
    from_step3 = models.DecimalField(_("From"), max_digits=9, decimal_places=4, default=0)
    to_step3 = models.DecimalField(_("To"), max_digits=9, decimal_places=4, default=0)
    viu_step3 = models.DecimalField(_("Viu"), max_digits=9, decimal_places=4, default=0)
    from_step4 = models.DecimalField(_("Less than"), max_digits=9, decimal_places=4, default=0)
    viu_step4 = models.DecimalField(_("Viu"), max_digits=9, decimal_places=4, default=0)
    min_weight_diff = models.DecimalField(_("Min weight difference"), max_digits=9, decimal_places=4, default=0)
    max_weight_diff = models.DecimalField(_("Max weight difference"), max_digits=9, decimal_places=4, default=0)
    platts = models.DecimalField(_("Platts contract"), max_digits=9, decimal_places=4, default=0)
    creator = models.ForeignKey('accounts.User', verbose_name=_("Creator"), related_name="deal_creator")
    created_date = models.DateTimeField(_("Project created date"), auto_now_add=True)
    is_deleted = models.BooleanField(_("Deleted"), default=False)
    objects = LogicalDeletedManager()

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.save()

    def __str__(self):
        return "%s - %s" % (self.vessel_name, self.agreement_no)

    # def get_bill_total(self):
    #     bill_slip = BillSlip.objects.filter(deal=self)
    #     total = 0
    #     for bill in bill_slip:
    #         total += bill.amount_to_dollar
    #     return total
    #
    # def get_residual(self):
    #     return self.total_price - (self.down_payment + self.get_bill_total())
    #
    # @staticmethod
    # def get_documents(deal_id):
    #     documents = DealDocumentSpec.objects.filter(deal_id=deal_id)
    #     result_list = dict()
    #     for document in documents:
    #         doc = str(document.field.document.name)
    #         if doc not in result_list:
    #             result_list[doc] = []
    #         result_list[doc].append(document)
    #     return result_list


class MyCompany(models.Model):
    name = models.CharField(_("Company name"), max_length=50, null=True, blank=True)
    address = models.TextField(_("Company address"), max_length=150, null=True, blank=True)
    phone_number = models.CharField(_("Company phone number"), max_length=15, null=True, blank=True)
    cell_phone_number = models.CharField(_("Cell phone number"), max_length=15, null=True, blank=True)
    email = models.EmailField(_("Email address"))
    is_deleted = models.BooleanField(_("Deleted"), default=False)
    objects = LogicalDeletedManager()

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.save()

    def __str__(self):
        return self.name


class Mine(models.Model):
    name = models.CharField(_("Mine"), max_length=50)
    owner = models.CharField(_("Mine owner"), max_length=50)
    company_name = models.CharField(_("Company name"), max_length=50, null=True, blank=True)
    company_address = models.TextField(_("Company address"), max_length=150, null=True, blank=True)
    company_phone_number = models.CharField(_("Company phone number"), max_length=15, null=True, blank=True)
    cell_phone_number = models.CharField(_("Cell phone number"), max_length=15, null=True, blank=True)
    email = models.EmailField(_("Email address"))
    location = models.TextField(_("Mine location"), null=True, blank=True)
    is_deleted = models.BooleanField(_("Deleted"), default=False)
    objects = LogicalDeletedManager()

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.save()

    def __str__(self):
        return self.name


class ShipDeal(models.Model):
    deal = models.OneToOneField('Deal', verbose_name=_('Deal'), related_name='ship_deal')
    destination = models.TextField(_("Destination port"))
    capacity = models.DecimalField(_("Capacity"), max_digits=9, decimal_places=4)
    cost = models.DecimalField(_("Cost per tone"), max_digits=9, decimal_places=4)
    deprecate_date = models.DateField(_("Departure date"))
    laycan_start = models.DateField(_("Ship laycan Start"))
    laycan_end = models.DateField(_("Ship laycan End"))
    bl_date = models.DateField(_("BL Date"))
    loading_start_date = models.DateField(_("Ship Loading Start date"))
    loading_rate = models.IntegerField(_("Loading rate"))
    discharge_rate = models.IntegerField(_("Discharge rate"))
    agent_name = models.CharField(_("Agent name"), max_length=50)
    agent_phone_number = models.CharField(_("Agent phone number"), max_length=15)
    is_deleted = models.BooleanField(_("Deleted"), default=False)
    objects = LogicalDeletedManager()

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.save()

    def __str__(self):
        return self.deal.ship.name


class BillSlip(models.Model):
    name = models.CharField(_("Bill name"), max_length=100)
    date = models.DateField(_("Date"))
    unit = models.ForeignKey('base_information.Currency', verbose_name=_('Currency'))
    deal = models.ForeignKey('Deal', verbose_name=_('Deal'), related_name='bill_slip')
    amount = models.DecimalField(_("Amount"), max_digits=15, decimal_places=4, default=0)
    amount_to_dollar = models.DecimalField(_("Amount In Dollar"), max_digits=15, decimal_places=4, default=0)
    description = models.TextField(_("Description"), null=True, blank=True)
    bank_slip_file = models.FileField(_("Bill Slip"), upload_to=bill_slip_upload_to, null=True, blank=True)

    def get_name(self):
        return "%s" % self.name


class DealDocumentSpec(models.Model):
    deal = models.ForeignKey('Deal', verbose_name=_(u"Deal"), related_name="document_spec_deal")
    field_type = models.IntegerField(_("Type"), choices=DocumentSpec.FIELD_TYPES)
    field = models.ForeignKey('base_information.DocumentSpec', verbose_name=_(u"Field Name"),
                              related_name="document_extra_fields")
    file = models.FileField(_("File"), upload_to=deal_file_upload_to, null=True, blank=True)
    value = models.TextField('Value', null=True, blank=True)

    def set_value(self, value):
        if self.field_type == DocumentSpec.FILE_TYPE:
            self.file = value
        else:
            self.value = value


class ProductDeal(models.Model):
    PENALTY_DEFAULT = 1
    PENALTY_STAIRS = 2
    PENALTY_FIXED = 3
    PENALTY_CHOICES = (
        (PENALTY_DEFAULT, _("Default")),
        (PENALTY_STAIRS, _("STAIRS")),
        (PENALTY_FIXED, _("FIXED")),
    )

    CONTRACT = 1
    SGS = 2
    CIQ = 3
    INFO_CHOICES = (
        (CONTRACT, _("Contract")),
        (SGS, _("Sgs")),
        (CIQ, _("Ciq")),
    )
    deal = models.ForeignKey('Deal', verbose_name=_(u"Deal"), related_name="product_deal")
    product = models.ForeignKey('base_information.Product', verbose_name=_(u"Product name"),
                                related_name="product_deal")

templates/deal/purchase/add_edit_purchase.html
{% extends "base/base.html" %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block BOTTOM_CSS %}
    <link href="{% static "css/plugin/select2/select2.min.css" %}" rel="stylesheet">
    <link href="{% static "css/plugin/iCheck/custom.css" %}" rel="stylesheet">
{% endblock %}
{% block CONTENT %}
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>{{ title }}</h5>
                </div>
                <div class="ibox-content">
                    {% include "partials/base/notif/messages.html" %}
                    <div class="row">
                        <div class="col-md-12">
                            <form method="post" class="form-horizontal" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="generalInfo">
                                    <h3>{% trans "General Information" %}</h3>
                                    {% for field in form %}
                                        {% if field.name in form.layout_general %}
                                            {% include "partials/base/forms/wide_form.html" %}
                                        {% endif %}
                                    {% endfor %}

                                    <div class="row">
                                        <label for="" class="col-sm-2 control-label"> Step 1
                                        <span class="required_field">*</span></label>
                                        <div class="col-md-3">
                                            <div class="form-group" id="data_1">
                                                <label class="font-noraml">{{ form.from_step1.label }}</label>
                                                <div class="input-group ">
                                                    {{ form.from_step1|add_class:"form-control" }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group" id="data_1">
                                                <label class="font-noraml">{{ form.viu_step1.label }}</label>
                                                <div class="input-group ">
                                                    {{ form.viu_step1|add_class:"form-control" }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label for="" class="col-sm-2 control-label"> Step 2
                                        <span class="required_field">*</span></label>
                                        <div class="col-md-3">
                                            <div class="form-group" id="data_1">
                                                <label class="font-noraml">{{ form.from_step2.label }}</label>
                                                <div class="input-group ">
                                                    {{ form.from_step2|add_class:"form-control" }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group" id="data_1">
                                                <label class="font-noraml">{{ form.to_step2.label }}</label>
                                                <div class="input-group ">
                                                    {{ form.to_step2|add_class:"form-control" }}
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-3">
                                            <div class="form-group" id="data_1">
                                                <label class="font-noraml">{{ form.viu_step2.label }}</label>
                                                <div class="input-group ">
                                                    {{ form.viu_step2|add_class:"form-control" }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label for="" class="col-sm-2 control-label"> Step 3
                                        <span class="required_field">*</span></label>
                                        <div class="col-md-3">
                                            <div class="form-group" id="data_1">
                                                <label class="font-noraml">{{ form.from_step3.label }}</label>
                                                <div class="input-group ">
                                                    {{ form.from_step3|add_class:"form-control" }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group" id="data_1">
                                                <label class="font-noraml">{{ form.to_step3.label }}</label>
                                                <div class="input-group ">
                                                    {{ form.to_step3|add_class:"form-control" }}
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-3">
                                            <div class="form-group" id="data_1">
                                                <label class="font-noraml">{{ form.viu_step3.label }}</label>
                                                <div class="input-group ">
                                                    {{ form.viu_step3|add_class:"form-control" }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label for="" class="col-sm-2 control-label"> Step 4
                                        <span class="required_field">*</span></label>
                                        <div class="col-md-3">
                                            <div class="form-group" id="data_1">
                                                <label class="font-noraml">{{ form.from_step4.label }}</label>
                                                <div class="input-group ">
                                                    {{ form.from_step4|add_class:"form-control" }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group" id="data_1">
                                                <label class="font-noraml">{{ form.viu_step4.label }}</label>
                                                <div class="input-group ">
                                                    {{ form.viu_step4|add_class:"form-control" }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="hr-line-dashed"></div>
                                <div class="button_holder">
                                    <button type="submit" class="btn btn-w-m btn-primary">{% trans "Save" %}</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block BOTTOM_JS %}
    <script src="{% static "js/plugin/select2/select2.full.min.js" %}"></script>
    <script src="{% static "js/plugin/iCheck/icheck.min.js" %}"></script>
    <script src="{% static "js/forms.js" %}"></script>
    <script src="{% static "js/deal.js" %}"></script>
    <script>
        $(document).ready(function () {
            $("#id_project_date").on('change', function (e) {
                $("#id_index_date").val($(this).val());
            });

            $('#id_index_types,#id_period,#id_index_date').on('change', function (e) {
                index_price();
            });
        });
    </script>
{% endblock %}

templates/deal/purchase/view_details_purchase.html
{% extends "base/base.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% load staticfiles %}
{% load common_template_tags %}
{% load humanize %}
{% block title %}{{ title }}{% endblock %}
{% block CSS %}
    {{ block.super }}
{% endblock %}
{% block CONTENT %}
    <div class="row">
        <div class="col-lg-2" style="">
            <table class="wide-table table btn-action">
                <tr>
                    <td><h2 style="text-align: center;font-size: 21px;">{% trans "Agreement Number" %}: <span
                            style="font-size:17px;"> {{ instance.agreement_no }}</span></h2></td>
                </tr>
                <tr>
                    <td>
                        <h3 style="font-weight: lighter; text-align: center;line-height: 1.5em;">{% trans 'Agreement registraion' %}:
                            <br> {{ instance.created_date | naturaltime }}</h3>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h3 style="font-weight: lighter; text-align: center;line-height: 1.5em;">{% trans 'Agreement State' %}:
                            <br> {{ instance.get_state_display }}</h3>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div style="min-height: 0px;"></div>
                    </td>
                </tr>
                {% if primary_btn %}
                    <tr>
                        <td>
                            <div style="min-height: 0px;"></div>
                        </td>
                    </tr>
                    {% for action in primary_btn %}
                        <tr>
                            <td>
                                <a class="btn btn-w-m action-button {{ action.btn_type }} vertical-btn"
                                   new_tab="{{ action.new_tab }}" is_view="True"
                                   is_popup="{{ action.is_popup }}" url_address="{{ action.url_address }}"
                                   spec_url="{{ action.spec_url }}" id="action_{{ action.btn_id }}"
                                   confirm_message="{{ action.swal_title }}" help_message="{{ action.swal_content }}"
                                   name="action_{{ action.name }}">{{ action.title }}{% if action.icon %}
                                    <i class="fa {{ action.icon }}"></i>{% endif %}</a>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </table>
        </div>
        <div class="col-lg-10">
            <div class="tabs-container">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#tab-1">{% trans "Agreement" %}</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-2">{% trans "Invoice" %}</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-3">{% trans "Documents" %}</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-4">{% trans "Bill Slip" %}</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-5">{% trans "Workflow" %}</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-6">{% trans "History" %}</a></li>
                </ul>
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane active">
                        <div class="panel-body">
                            {% include 'deal/partials/_block_view.html'  with instance=instance %}
                        </div>
                    </div>
                    <div id="tab-2" class="tab-pane ">
                        <div class="panel-body">
                            {% for ins in invoices %}
                                {% include 'deal/partials/_block_view.html'  with instance=ins %}
                            {% endfor %}
                        </div>
                    </div>
                    <div id="tab-3" class="tab-pane ">
                        <div class="panel-body">
                            {% for key,value in documents.items %}
                                {% include 'deal/_document_view.html' %}
                            {% endfor %}
                        </div>
                    </div>
                    <div id="tab-4" class="tab-pane ">
                        <div class="panel-body">
                            {% for bill in instance.deal_bill_slip.all %}
                                {% include 'deal/_bill_slip_view.html' %}
                            {% endfor %}
                        </div>
                    </div>
                    <div id="tab-5" class="tab-pane ">
                        <div class="panel-body">
                            {% for workflow in instance.worflow_deal.all %}
                                {% include 'deal/_workflow_view.html' with instance=instance %}
                            {% endfor %}
                        </div>
                    </div>
                    <div id="tab-6" class="tab-pane ">
                        <div class="panel-body">
                            {% for history in instance.history_deal.all %}
                                {% include 'deal/partials/_history_view.html' %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'partials/base/_modal.html' %}
{% endblock %}
{% block BOTTOM_JS %}
    {{ block.super }}
    <script src="{% static "js/deal.js" %}"></script>

    <script>
        $(document).ready(function () {
            $('.action-button').on('click', function (e) {
                action_click($(this));
            });
        });
    </script>
{% endblock %}